config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :contacts
  resources :comments
  resources :graphs

  get "/messages/received" => 'messages#getReceivedMessages'
  get "/messages/sent" => 'messages#getSentMessages'
  get "/connections/received" => 'connections#getReceivedRequests'
  get "/connections/sent" => 'connections#getSentRequests'

  resources :messages
  resources :connections

  root :to =>'welcome#index'
  get "/users/sign_out.:id" => 'users#custom_sign_out'
  get "/users/:id/inbox/" => 'users#inbox'
  get 'messages/:id/message_data', to: 'messages#message_data'
  get "/users/current_user" => 'users#getCurrentUser'
  get "/messages/chain/:id" => 'messages#messageHistory'

  resources :users do
    resources :graphs
  end

  post '/users/:user_id/graphs/upload' => 'graphs#upload', as: 'users_graphs_upload'
  post "/users/:user_id/graphs/:id/send_mail" => "graphs#send_mail", as: 'user_graphs_email'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/graph.rb
class Graph < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  # before_action :authenticate_user!
  # before_action :validate_current_user_graphs
  require 'csv'

  def upload
    if params[:file]
      @csv_file = params[:file].path
      @graph = current_user.graphs.build(title:params[:title], description:params[:description],
      data_label:params[:data_label])
      csv_parser = CsvParser.new
      csv_parser.format_data(@csv_file, @graph, current_user)
    else
      flash[:message] = "Please upload a CSV file"
    end
    redirect_to user_path(current_user)
  end

  def send_mail

    graph = params[:chart]
    email = params[:recipient]
    message = params[:message]

    @email = Emailer.new
    @email.open_file(current_user.name,email,graph)
    @email.send_email(message)

    render :json => {"message": "success"}
  end

  def new
  end

  def create

  end

  def show
    @graph = current_user.graphs.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @graph}

    end
  end

  def edit
    @graph = Graph.find(params[:id])
    respond_to do |format|
      format.html {render :edit}
    end
  end

  def update
    @graph = current_user.graphs.find(params[:id])
    updated_data = params["graphData"].values
    csv_parser = CsvParser.new
    csv_parser.update_data(@graph,updated_data)
    respond_to do |format|
      format.json {render json: @graph}
    end
  end


  def index
    @graphs = current_user.graphs
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @graphs}
    end
  end

end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/views/graphs/_graph.html.erb
<canvas id="myChart" width="200" height="200"></canvas>
<script>
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

</script>

app/views/graphs/_graphs.html.erb
<input id="user_id" type="hidden" name="user_id" value="<%=current_user.id%>">
<div class="container" style= "width: 510px; height: 500px;">
  <h1 id="empty" class="w3-center">Upload data to begin</h1>
<!-- <canvas id="myChart" max-width="400" max-height="400" height="700" width="900" style= "width: 510px; height: 500px;"></canvas> -->
</div>

app/views/graphs/_upload.html.erb
  <%= form_tag users_graphs_upload_path(current_user), multipart: true do %>
  Chart Title: <input type="text" name="title" value="">
  Data Points: <input type="text" name="data_label" value="">
  <br>
  <br>
  Description:<textarea name="description" rows="5" cols="40"></textarea>
    <%= file_field_tag :file %>
    <br>
    <%= submit_tag "Upload CSV", class:'w3-btn w3-round-small w3-blue' %>
    <% end%>

app/views/graphs/edit.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">

<input id="user_id" type="hidden"  value="<%=current_user.id%>">
<input id="graph_id" type="hidden" value="<%=@graph.id%>">
<!--  button change data-->
<div class="button">
  <p><button id = "changeData" class="w3-btn w3-round-large w3-blue">Change Data</button></p>
  <br><br>
  <p><button id="save-btn" class="w3-btn w3-round-large w3-blue">Download Chart</button></p>
  <br><br>

</div>
<div class="right_button">

  <form class="email" action="/users/<%=current_user.id%>/graphs/<%=@graph.id%>/send_mail" method="post">
    <div class="recp">
      <b>Recipent(s) Email:</b><input id="recipient" type="text" name="recipient" value="" placeholder="john@example.com"></input>
    </div>
    <br>
    <b>Message:</b><textarea id="message" type="text" name="name" value="" rows="4" cols="20" placeholder="..."></textarea>
    <br> <br>
    <input id="email-btn" type="submit" name="Email" class="w3-btn w3-round-large w3-blue" value="Email">
  </form>

</div>
<!--  -->
<div class="outer" style= "width: 610px; height: 600px; margin-left:auto; margin-right:auto;">
  <div class="edit_graph" styling="margin-left:50px;">

  </div>
</div>


<div id="data">
  <form class="dataUpdate" action="/users/<%=current_user.id%>/graphs/<%=@graph.id%>" method="patch">
    <table id="table_data">
      <tr id="header">

      </tr>
      <tr id="data_values">

      </tr>
    </table>

  </form>

</div>

<!-- Pop up Modal -->
<div id="id01" class="w3-modal">
      <div class="loader"></div>
  </div>
<!--  -->

app/views/graphs/index.html.erb
<%= render 'graphs/upload' %>